# Generated by Django 5.1.5 on 2025-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_books', models.IntegerField(default=0)),
                ('read_books', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goal',
            },
        ),
    ]
